### ISSUE TITLE
Changing i2c address

### ISSUE THREAD

**Issue by strikerdlm** [paulvha/multichannel-gas#2] opened 2018-11-14 10:56 UTC
The program works fine with the address assigned to 0x04 (factory setting), I tried to change it using sudo ./gass -a 3c and it did because I have other sensors like MPU-9250 and BMP280 and they stopped working after getting readings from ./gass -s 1. after that change the output shows that the library does not support old V1 firmware (I use a V1 sensor). Where can I change the code to make it work with the new i2c address (0x3c) or how can I restore the original 0x04 address. Thank you
PD (using sudo ./gass -a 04 does not revert the changes nor reseting to factory settings with ./gass -f)

**Comment by paulvha** [comment] 2018-11-14 20:53
hi

To change :

Make sure that the multichannel-gas sensor is the ONLY sensor connected to the i2C channel.
Then run ./gass -f. it will then try to detect an I2C device on the channel ( between 0 and 127). It will assume that this is the multichannel gas sensor and try to restore to 0x4.

The BMP280 should NOT be a concern. That has either do 0x77 or 0x76.
The MP9250 is normally either  0x68 or 0x69.

I think the issue is that once you changed to a new address (0x3c in your case), the next time you run the program( gass -s 1) the program is not using 0x3c (in your case)  but still assumes the default ( 0x4) and thus fails.  I had not included an option to set for a different I2 address in the gass in that case, which I should have done. The best is to change back again.

regards,
Paul
________________________________
Van: strikerdlm <notifications@github.com>
Verzonden: woensdag 14 november 2018 11:56
Aan: paulvha/multichannel-gas
CC: Subscribed
Onderwerp: [paulvha/multichannel-gas] Changing i2c address (#2)


The program works fine with the address assigned to 0x04 (factory setting), I tried to change it using sudo ./gass -a 3c and it did because I have other sensors like MPU-9250 and BMP280 and they stopped working after getting readings from ./gass -s 1. after that change the output shows that the library does not support old V1 firmware (I use a V1 sensor). Where can I change the code to make it work with the new i2c address (0x3c) or how can I restore the original 0x04 address. Thank you
PD (using sudo ./gass -a 04 does not revert the changes nor reseting to factory settings with ./gass -f)

**Comment by strikerdlm** [comment] 2018-11-14 21:31
Yes, it worked perfectly. Thank you

**Closed as completed** 2018-11-14 21:31 UTC
